Webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learn_log.urls')),
]

learn_log/urls.py
"""定义 learn_log 的 URL 模式"""  # 文档字符串，用于指出该 urls.py 文件位于哪个 app 中

from django.urls import path  # 使用 path 将 URL 映射到视图中

from . import views

app_name = 'learn_log'  # 用于与其他 urls.py 文件区分开

"""
    path函数的三个实参:
        1.是个字符串，帮助 Django 正确的 route 请求。请求时，会搜索所有的 URL pattern ，
        找到匹配的那个。Django 会忽略基础 URL(http://localhost:8000/), 故''(空字符串)会与基础 URL 匹配
        2.指定调用 views.py 文件中的函数，若 URL 与 1. 中表达式匹配，则会调用 views 中的 index() 函数
        3.将该 URL pattern 命名为 'index' 便于其他地方引用
"""
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    # 显示所有主题
    path('topics/', views.topics, name='topics'),
    # 显示特定主题的详细页面
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # 用于添加新主题的页面
    path('new_topic/', views.new_topic, name='new_topic'),
    # 用于添加新条目的页面
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # 用于修改特点条目的页面
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry')
]

users/urls.py
"""为 app users 建立 URL pattern"""

from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    # 包含默认身份验证的 URL
    path('', include('django.contrib.auth.urls')),
    # 注册页面
    path('register/', views.register, name='register'),
]

learn_log/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Topic(models.Model):
    """用户储存学习知识的主题"""
    text = models.CharField(max_length=200)  # 储存主题的名字
    date = models.DateTimeField(auto_now_add=True)  # 自动记录主题创建的时间
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    """用户学习到的有关某个主题的具体知识"""

    """
    外键, 数据库术语，指向数据库中的另一条记录，这里指将条目关联到具体的主题
    on_delete=models.CASCADE 用于实现删除主题时，同时删除与之相关联的条目，称为 级联删除(cascading delete)
    """
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    """Meta类 用于储存管理模型的额外信息"""

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回该模型的字符串表示"""
        if len(self.text) >= 50:
            return f'{self.text[:50]}...'
        else:
            return f'{self.text}'

users/models.py
from django.db import models

# Create your models here.

learn_log/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):

    """Meta 类告诉 Django 根据哪个模型创建表单，以及在表单中包含哪些字段"""
    class Meta:
        model = Topic  # 告诉 Django 根据 Topic 创建表单
        fields = ['text']  # 只包含 text 一个字段
        labels = {'text': ' '}  # 让 Django 不为 text 生成标签


class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ' '}
        """
        widgets，HTML 中的小部件，表单元素
        设置 widgets 属性，可覆盖 Django 选择的默认小组件
        通过让 Django 使用 forms.Textarea，定制 text 的输入小部件
        """
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learn_log/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect  # render() 函数用于根据视图提供的数据渲染响应

from .forms import TopicForm, EntryForm
from .models import Topic, Entry


# Create your views here.
def index(request):
    """学习笔记的主页"""
    return render(request, 'learn_log/index.html')


@login_required
def topics(request):
    """显示所有的主题"""
    _topics = Topic.objects.filter(owner=request.user).order_by('date')  # 从数据库中获取数据，限制用户访问，并按日期排序
    context = {'topics': _topics}  # 定义一个上下文，上下文是一个字典，用于传给模板，其中键值模板中用来访问的数据名称，值为发送给模板是数据
    return render(request, 'learn_log/topics.html', context)


@login_required
def topic(request, topic_id):
    """显示单个主题，及其所有条目"""
    _topic = Topic.objects.get(id=topic_id)  # 该操作称为查询，建议先在 Django shell 中验证一下结果，再写进代码
    __check_topic_owner(_topic, request)

    entries = _topic.entry_set.order_by('-date')  # -号表示降序排列
    context = {'topic': _topic, 'entries': entries}
    return render(request, 'learn_log/topic.html', context)


@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # 对 POST 提交的数据进行处理
        form = TopicForm(data=request.POST)
        if form.is_valid():
            _new_topic = form.save(commit=False)
            _new_topic.owner = request.user
            _new_topic.save()
            return redirect('learn_log:topics')

    context = {'form': form}
    return render(request, 'learn_log/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """在特定主题中添加新条目"""
    _topic = Topic.objects.get(id=topic_id)
    __check_topic_owner(_topic, request)

    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = EntryForm()
    else:
        # 对 POST 提交的数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            _new_entry = form.save(commit=False)  # 让 Django 创建一个新的条目对象但不储存到数据库中
            _new_entry.topic = _topic  # 使新的 entry 匹配相应的 topic
            _new_entry.save()  # 保存新的 entry 到数据库中
            return redirect('learn_log:topic', topic_id=topic_id)

    context = {'topic': _topic, 'form': form}
    return render(request, 'learn_log/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """修改已有条目"""
    _entry = Entry.objects.get(id=entry_id)
    _topic = _entry.topic
    __check_topic_owner(_topic, request)

    if request.method != 'POST':
        form = EntryForm(instance=_entry)
    else:
        form = EntryForm(instance=_entry, data=request.POST)  # 根据既有条目对象创建一个表单，数据使用 POST 中的数据
        if form.is_valid():
            form.save()
            return redirect('learn_log:topic', topic_id=_topic.id)

    context = {'topic': _topic, 'entry': _entry, 'form': form}

    return render(request, 'learn_log/edit_entry.html', context)


def __check_topic_owner(_topic, request):
    if _topic.owner != request.user:
        raise Http404

users/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


# Create your views here.
def register(request):
    """注册新用户"""
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)  # 用于用户正确填写表单后自动登录
            return redirect('learn_log:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

learn_log/templates/learn_log/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>

<nav class="navbar navbar-expand-md navbar-light bg-light md-4 border">
    <a class="navbar-brand" href="{% url 'learn_log:index' %}">Learning Log</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'learn_log:topics' %}">Topics</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log In</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</main>
</body>
</html>

learn_log/templates/learn_log/edit_entry.html
{% extends 'learn_log/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h1><a href="{% url 'learn_log:topic' topic.id %}">{{ topic }}</a></h1>
{% endblock page_header %}

{% block content %}
    <h4>Edit Entry:</h4>
    <form action="{% url 'learn_log:edit_entry' entry.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Submit Change</button> <!-- 为表单创建提交按钮 -->
        {% endbuttons %}
    </form>
{% endblock content %}

learn_log/templates/learn_log/index.html
{% extends "learn_log/base.html" %}

{% block page_header %}

    <div class="container" style="margin-top: 20px">
        <div class="jumbotron">
            <h1 class="display-3">Track your learning.</h1>

            <p class="lead">Make your own Learning Log, and keep a list of the topics you're learning about.
                Whenever you learn something new about a topic, make an entry summarizing what you've learned.</p>

            {% if request.user.is_authenticated %}
                <a href="{% url 'learn_log:topics' %}" class="btn btn-lg btn-primary" role="button">&nbsp;Start &raquo;</a>
            {% else %}
                <a href="{% url 'users:register' %}" class="btn btn-lg btn-primary" role="button">Register &raquo;</a>
            {% endif %}
        </div>
    </div>

{% endblock page_header %}

learn_log/templates/learn_log/new_entry.html
{% extends 'learn_log/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h1><a href="{% url 'learn_log:topic' topic.id %}">{{ topic }}</a></h1>
{% endblock page_header %}

{% block content %}
    <h4>Add A New Entry :</h4>
    <form action="{% url 'learn_log:new_entry' topic.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add Entry</button> <!-- 为表单创建提交按钮 -->
        {% endbuttons %}
    </form>
{% endblock content %}

learn_log/templates/learn_log/new_topic.html
{% extends 'learn_log/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Add a new topic</h1>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'learn_log:new_topic' %}" method="post" class="form">
        <!-- action 告诉表单数据发送到哪里，此处发送到 views.py 中的 new_topic()函数中 -->
        {% csrf_token %}  <!-- 防止攻击者对服务器进行未授权的访问 -->
        {% bootstrap_form form %}  <!-- 显示表单， .as_p 表示 Django 将会以段落格式渲染元素 -->

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add Topic</button> <!-- 为表单创建提交按钮 -->
        {% endbuttons %}
    </form>
{% endblock content %}

learn_log/templates/learn_log/topic.html
{% extends 'learn_log/base.html' %}

{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'learn_log:new_entry' topic.id %}">Add A New Entry</a>
    </p>


    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date|date:'M d, Y H:i' }}
                <small><a href="{% url 'learn_log:edit_entry' entry.id %}">Edit Entry</a></small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no entries for this topic yet.</p>
    {% endfor %}


{% endblock content %}

learn_log/templates/learn_log/topics.html
{% extends 'learn_log/base.html' %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li><h3>
                <a href="{% url 'learn_log:topic' topic.id %}">{{ topic }}</a>
            </h3></li>
        {% empty %}
            <li><h3>No topics have been added yet.</h3></li>
        {% endfor %}
    </ul>

    <h3><a href="{% url 'learn_log:new_topic' %}">Add A New Topic</a></h3>
{% endblock content %}